---
title: "Cheem example: FIFA"
author: "Nicholas Spyrison"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---
<!--   #rmarkdown::html_vignette -->
<!-- # vignette: > -->
<!-- #   %\VignetteIndexEntry{spinifex} -->
<!-- #   %\VignetteEngine{knitr::rmarkdown} -->
<!-- #   %\VignetteEncoding{UTF-8}{inputenc} -->
<!-- #   \usepackage[utf8]{inputenc} -->

<!-- #Example vignette: 
https://github.com/njtierney/naniar/blob/master/vignettes/getting-started-w-naniar.Rmd -->
```{r setup, include = FALSE}
knitr::opts_chunk$set(
  echo       = TRUE,   # code
  include    = TRUE,   # plots
  eval       = TRUE,   # chunk
  message    = FALSE,
  warning    = FALSE,
  error      = FALSE,
  collapse   = TRUE,
  cache = TRUE
)
```

# Example application of Trees of Cheem

Here we start with the intro `trees_of_cheem.rmd` applied to tourr::flea data and set off to recreate for DALEX::fifa. We have a sizeable set, with many classes, so we'll also apply `{tictoc}` do get a sense of performance

## Requirements

```{R}
require("DALEX")
require("treeshap")
#devtools::install_github('ModelOriented/treeshap')
require("spinifex")
require("tourr")
require("ggplot2")
## esp. for basis_cheem() and view_cheem()
#### basic examples also given in file.
source("../apps/poc/trees_of_cheem.r") 
# file.edit("./apps/poc/trees_of_cheem.r")
require("tictoc")
```

## Data setup

```{R}
raw <- DALEX::fifa

## subset for performance
require(dplyr)
.top_nationality <-
  table(raw$nationality) %>%
  as.data.frame() %>%
  top_frac(.25)
## Removes 20% of obs to reduced class levels by 75%
#### remove the filtered nationalities from the levels.
sub <- raw %>% 
  filter(nationality %in% .top_nationality$Var1) %>% 
  mutate(nationality = as.factor(as.character(nationality))) 


str(sub)
.rn <- row.names(sub)
tgt_name <- "L. Messi"

std_df <- spinifex::scale_sd(sub[, -1])
holdout_obs <- which(.rn == tgt_name)

dat <- std_df[-holdout_obs, ]
oos_obs <- std_df[holdout_obs,, drop = FALSE] ## Keep as a data.frame
clas <- sub[-holdout_obs, 1]
oos_clas <- sub[holdout_obs, 1]
```

## Find a start basis

```{r}
message("There is an error with Rdimtools::do.olda(). Due to the sparsity of the class vector? we'll fall back to pca for robustness.")


{
  tic("basis_cheem()")
  cheem_bas <- basis_cheem(
    data = dat,
    class = clas,
    new_observation = oos_obs,
    new_observation_class = oos_clas,
    ## Selecting DALEX::predict_parts()
    parts_type = "shap", ## expects 'shap', 'break_down' or 'break_down_interactions'
    parts_B = 10,
    parts_N = NULL,
    ## Selecting spinifex::basis_*(), expects 'olda', 'pca', 'odp' or 'onpp'
    basis_type = "pca")
  ## ... passes to DALEX::predict_parts()
  toc()
  ## raw: 127 sec, top 25% nationalities, (80% obs) 88sec
}
```

## View the starting basis

```{r}
##TODO: another error;
# Error in `[.data.frame`(df, setdiff(names(df), names(transformed))) : 
#   undefined columns selected
# In addition: Warning message:
# Duplicated aesthetics after name standardisation: 
### IIRC this is is the same issue that came up when trying to abstract spinifex functions...
# debugonce(view_cheem)
# debugonce(view_frame)
paste0("view_cheem: ", tgt_name)
view_cheem(cheem_basis = cheem_bas,
           show_parts = TRUE)
## ... passes to DALEX::plot.predict_parts()
```

## Tour the space

### Short cheem tour, 4 target bases

```{r}
if(interactive())
  ?spinifex::play_tour_path()
## tour_path wants an array of target bases to tourr::interpolate() between.

## Let's naively find different cheem bases where SHAP is always on X and we find different first components for Y.
.bas_types <- c('pca', 'odp', 'onpp') ## 'olda'
tgt_bases <- array(NA, dim = c(dim(cheem_bas), length(.bas_types))) ## init
.mute <- sapply(seq_along(.bas_types), function(i){
  tgt_bases[,, i] <<-
    basis_cheem(dat, clas, oos_obs, oos_clas,
                ## X axis is always this SHAPely values
                parts_type = "shap",
                parts_B = 10,
                parts_N = NULL,
                ## Vary across components on Y axis, expects 'olda', 'pca', 'odp' or 'onpp'
                basis_type = .bas_types[i])
})
## Format for tourr::interpolate() 
tgt_bases <- as_history_array(tgt_bases, dat)

## Aesthetic init
.colorPal <- RColorBrewer::brewer.pal(8, "Dark2")
.col <- .colorPal[as.integer(clas)]
.col[holdout_obs] <- "red"
.shp <- as.integer(clas)
.shp[holdout_obs] <- 4 ## shape 8 is *
.alp <- rep(0.4, nrow(dat))
.alp[holdout_obs] <- .7
.siz <- rep(1.5, nrow(dat))
.siz[holdout_obs] <- 6

## Tour animation
spinifex::play_tour_path(
  tour_path = tgt_bases, 
  data = dat,
  ## position of the basis unit circle
  ## expects:  "center", "left", "right", "bottomleft", "topright", or "off"
  axes = "left", 
  angle = .15, ## step size distance between interpolation planes 
  fps = 8, 
  ## list that would go inside ggplot2::geom_point(aes(X))
  aes_args = list(), 
  ## list that would go inside geom, outside aes: ggplot2::geom_point(aes(), X)
  identity_args = list(color = .col, shape = .shp,
                       size = .siz, alpha = .alp),
  ## list of items to "add" to a ggplot() + X
  ggproto = list(spinifex::theme_spinifex()),
  ## expects render_gganimate (.gif) or render_plotly (.html widget)
  render_type = render_plotly,
  tooltip = c("id") ## only adds tool tips on axes segmetns not projection points.
)
## For saving, store output of spinifex::play_tour_path()
# ?gganimate::anim_save() ## with render_gganimate
# ?htmlwidgets::saveWidget() ## with render_gganimate
```
