---
title: "Trees of Cheem"
author: "Nicholas Spyrison"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---
<!--   #rmarkdown::html_vignette -->
<!-- # vignette: > -->
<!-- #   %\VignetteIndexEntry{spinifex} -->
<!-- #   %\VignetteEngine{knitr::rmarkdown} -->
<!-- #   %\VignetteEncoding{UTF-8}{inputenc} -->
<!-- #   \usepackage[utf8]{inputenc} -->

<!-- #Example vignette: 
https://github.com/njtierney/naniar/blob/master/vignettes/getting-started-w-naniar.Rmd -->
```{r setup, include = FALSE}
knitr::opts_chunk$set(
  echo       = TRUE, ## code
  include    = TRUE, ## plots
  eval       = TRUE, ## chunk
  message    = FALSE,
  warning    = FALSE,
  error      = FALSE,
  collapse   = TRUE
)
## Set dir relative to package
knitr::opts_knit$set(root.dir = '..')
```

# Intro to trees of cheem

## Requirements

```{R}
require("DALEX")
#require("treeshap")
require("spinifex")
require("tourr")
require("ggplot2")
## Especially, see basis_cheem() and view_cheem()
source("./apps/poc/trees_of_cheem.r")
## New spinifex ggproto_* api
source("./apps/poc/spinifex_ggproto.r")
if(F)
  file.edit("./apps/poc/trees_of_cheem.r")
```

## Data setup

```{R}
str(tourr::flea) ## 74 x 6 numeric + 3 level class
dat <- spinifex::scale_sd(tourr::flea[, 1:6])
clas <- tourr::flea$species
new_obs <- 20
tgt_var <- clas == clas[new_obs] ## Or regression on a continuous var not in data.
```

## Find a start basis

```{r}
bas_cheem <- basis_cheem(
  data = dat,
  holdout_rownum = new_obs,
  target_var = tgt_var,
  class = clas,
  ## Selecting DALEX::predict_parts(), ## "shap" to x axis.
  parts_type = "shap", ## Expects 'shap', 'break_down' or 'break_down_interactions'
  ## Selecting spinifex::basis_*(), expects 'olda', 'pca', 'odp' or 'onpp'
  basis_type = "olda") ## first component of olda to y axis.
```

## View a cheem basis

```{r}
view_cheem(cheem_basis = bas_cheem, show_parts = TRUE)
```


## Tour the space

### Short cheem tour, 4 target bases

```{r}
if(interactive())
  ?spinifex::play_tour_path()
## tour_path wants an array of target bases to tourr::interpolate() between.

## Let's naively find different cheem bases where SHAP is always on X and we find different first components for Y.
.bas_types <- c('RF_importance', 'olda', 'pca', 'odp', 'onpp')
tgt_bases <- array(NA, dim = c(dim(bas_cheem), length(.bas_types))) ## init
mute <- sapply(seq_along(.bas_types), function(i){
  tgt_bases[,, i] <<-
    bas_cheem <- basis_cheem(
      data = dat,
      class = clas,
      holdout_rownum = new_obs,
      target_var = tgt_var,
      ## X axis is always SHAPely values
      parts_type = "shap",
      ## Vary across components on Y axis, expects 'olda', 'pca', 'odp' or 'onpp'
      basis_type = .bas_types[i])
})
## Format for tourr::interpolate() 
tgt_bases <- as_history_array(tgt_bases, dat)

## Aesthetic init
.colorPal <- RColorBrewer::brewer.pal(8, "Dark2")
.col <- .colorPal[as.integer(clas)]
.col[new_obs] <- "red"
.shp <- as.integer(clas)
.shp[new_obs] <- 8 ## shape 8 is *, 4 is x
.alp <- rep(0.4, nrow(dat))
.alp[new_obs] <- .7
.siz <- rep(1.5, nrow(dat))
.siz[new_obs] <- 6

## Tour animation
spinifex::play_tour_path(
  tour_path = tgt_bases,
  data = dat,
  ## position of the basis unit circle
  ## expects:  "center", "left", "right", "bottomleft", "topright", or "off"
  axes = "left", 
  angle = .05, ## Step size distance [radians] between interpolation planes
  fps = 8, 
  ## list that would go inside ggplot2::geom_point(aes(X))
  aes_args = list(), 
  ## list that would go inside geom, outside aes: ggplot2::geom_point(aes(), X)
  identity_args = list(color = .col, shape = .shp,
                       size = .siz, alpha = .alp),
  ## list of items to "add" to a ggplot() + X
  ggproto = list(spinifex::theme_spinifex()),
  ## expects render_gganimate (.gif) or render_plotly (.html widget)
  render_type = render_plotly
)
## For saving, store output of spinifex::play_tour_path()
# ?gganimate::anim_save() ## with render_gganimate
# ?htmlwidgets::saveWidget() ## with render_gganimate
```

### Cheem tour, useing new api; `ggproto_*` 

Note that aesthetics are still a pain, for the oos obs case.

```{r}
## Aesthetic init
.colorPal <- RColorBrewer::brewer.pal(8, "Dark2")
.col <- .colorPal[as.integer(clas)]
.col[new_obs] <- "red"
.shp <- as.integer(clas)
.shp[new_obs] <- 8 ## shape 8 is *, 4 is x
.alp <- rep(0.4, nrow(dat))
.alp[new_obs] <- .7
.siz <- rep(1.5, nrow(dat))
.siz[new_obs] <- 6

## Sourced above:
#source("../apps/poc/spinifex_ggproto.r")
ggt <-
  ggplot_tour(tgt_bases, dat) +
  ggproto_basis_axes() +
  ggproto_data_points(identity_args = list(color = .col, shape = .shp,
                                           size = .siz, alpha = .alp)) +
  ggproto_data_background()

animate_plotly(ggt)
```

### Frozen tour route

```{r, eval=FALSE}
if(interactive())
  ?tourr::frozen_tour

## Create a freezing matrix of dim == basis
freezer_mat <- matrix(NA, nrow = nrow(cheem_bas), ncol = ncol(cheem_bas))
## Try to freeze the first columns, the SHAP values.
freezer_mat[, 1] <- .99 * (1 / nrow(cheem_bas))

## Tour attempt erroring
if(interactive())
  tourr::animate_xy(data = dat,
                    tour_path = tourr::frozen_tour(frozen = freezer_mat),
                    start = cheem_bas)
## R> Error in svd(t(Fa) %*% Fz) : infinite or missing values in 'x'
```

